Sitegeist:
  Taxonomy:
    contentRepository:
      rootNodeName: 'taxonomies'
      rootNodeType: 'Sitegeist.Taxonomy:Root'
      vocabularyNodeType: 'Sitegeist.Taxonomy:Vocabulary'
      taxonomyNodeType: 'Sitegeist.Taxonomy:Taxonomy'

Neos:
  Neos:
    modules:
      management:
        submodules:
          taxonomies:
            label: "Taxonomies"
            controller: \Sitegeist\Taxonomy\Controller\ModuleController
            description: 'Manage Taxonomies'
            icon: icon-tags
            privilegeTarget: 'Sitegeist.Taxonomy:Module.Show'

  Fusion:
    defaultContext:
      Taxonomy: \Sitegeist\Taxonomy\Eel\TaxonomyHelper
