Sitegeist:
  Taxonomy:
    contentRepository:
      rootNodeType: '%Sitegeist\Taxonomy\Package::ROOT_NODE_TYPE%'
      vocabularyNodeType: '%Sitegeist\Taxonomy\Package::VOCABULARY_NODE_TYPE%'
      taxonomyNodeType: '%Sitegeist\Taxonomy\Package::TAXONOMY_NODE_TYPE%'

Neos:
  Neos:
    modules:
      management:
        submodules:
          taxonomies:
            label: "Taxonomies"
            controller: \Sitegeist\Taxonomy\Controller\ModuleController
            description: 'Manage Taxonomies'
            icon: icon-tags
            privilegeTarget: 'Sitegeist.Taxonomy:Module.Show'

  Fusion:
    defaultContext:
      Taxonomy: \Sitegeist\Taxonomy\Eel\TaxonomyHelper
