Sitegeist:
  Taxonomy:
    contentRepository:
      rootNodeName: 'taxonomies'
      rootNodeType: 'Sitegeist.Taxonomy:Root'
      vocabularyNodeType: 'Sitegeist.Taxonomy:Vocabulary'
      taxonomyNodeType: 'Sitegeist.Taxonomy:Taxonomy'

  Silhouettes:
    properties:
      taxonomyReferences:
        type: references
        ui:
          label: 'Taxonomy References'
          inspector:
            editorOptions:
              nodeTypes: ['Sitegeist.Taxonomy:Taxonomy']
              startingPoint: '/taxonomies'
              placeholder: 'assign Taxonomies'

Neos:
  Neos:
    modules:
      management:
        submodules:
          taxonomies:
            label: 'Sitegeist.Taxonomy:Main:module.label'
            controller: \Sitegeist\Taxonomy\Controller\ModuleController
            description: 'Sitegeist.Taxonomy:Main:module.description'
            icon: fas fa-tags
            privilegeTarget: 'Sitegeist.Taxonomy:Module.Show'
    userInterface:
      translation:
        autoInclude:
          Sitegeist.Taxonomy:
            - 'Main'
            - 'NodeTypes/*'

  Fusion:
    defaultContext:
      Taxonomy: \Sitegeist\Taxonomy\Eel\TaxonomyHelper
