Sitegeist:
  Taxonomy:
    contentRepository:
      rootNodeName: 'taxonomies'
      rootNodeType: 'Sitegeist.Taxonomy:Root'
      vocabularyNodeType: 'Sitegeist.Taxonomy:Vocabulary'
      taxonomyNodeType: 'Sitegeist.Taxonomy:Taxonomy'

  Silhouettes:
    properties:
      taxonomyReferences:
        type: references
        ui:
          label: 'Taxonomy References'
          inspector:
            editorOptions:
              nodeTypes: ['Sitegeist.Taxonomy:Taxonomy']
              startingPoint: '/taxonomies'
              placeholder: 'assign Taxonomies'

Neos:
  Neos:
    modules:
      management:
        submodules:
          taxonomies:
            label: "Taxonomies"
            controller: \Sitegeist\Taxonomy\Controller\ModuleController
            description: 'Manage Taxonomies'
            icon: icon-tags
            privilegeTarget: 'Sitegeist.Taxonomy:Module.Show'

  Fusion:
    defaultContext:
      Taxonomy: \Sitegeist\Taxonomy\Eel\TaxonomyHelper
